### ISSUE TITLE
Grouping scans into folders

### ISSUE THREAD

**Issue by cromination** [springernature/pa11y-dashboard#294]
Dashboard performance tends to be very slow when a large number of cards (over 100) are being rendered on page load, especially if a user wants to view only a particular website or sections of a larger site.  This could be improved by grouping those scans into folders and only rendering the top level cards in a given folder view.  i.e. the main view of the application can be configured to list a series of folders.  A user clicks into those folders and then has a series of scan results in there they can review.

**Comment by josebolos** [comment]
Hi @cromination.

Thanks for creating this issue. Your issue looks very similar to #254 so I'm closing it as a duplicate. Please follow up #254 for updates.
